{% set name = "ssh2-python" %}
{% set version = GIT_DESCRIBE_TAG %}
# {% set sha256 = "e5e77801a7a0d49799e288ecbd189b4d1c23eeadcf9c6f4ce80b31b7d397babe" %}

package:
  name: {{ name|lower }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../
  fn: {{ name }}-{{ GIT_DESCRIBE_TAG }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: {{ sha256 }}

build:
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]
  # skip: true  # [win]
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record record.txt  # [unix]
    - rm -f ssh2/*.c  # [win]
    - python setup.py build_ext --compiler=msvc  # [win]
    - python setup.py install --single-version-externally-managed --record record.txt  # [win]

requirements:
  build:
    - python
    - cython
    - setuptools
    - gcc  # [unix]
    - libssh2
    - openssl 1.0.*
  run:
    - python
    - libssh2
    - gcc  # [unix]
    - openssl 1.0.*

test:
  imports:
    - ssh2.session

about:
  home: http://github.com/ParallelSSH/ssh2-python
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE
  summary: 'Super fact SSH library. Based on libssh2.'

  description: |
    Super fast SSH2 protocol library.

    ssh2-python provides Python bindings for libssh2.

    Its only dependency is the libssh2 library.
  dev_url: https://github.com/ParallelSSH/ssh2-python

extra:
  recipe-maintainers:
    - pkittenis
